version: '2'
services:
    hilfie-app:
        image: hilfie
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://hilfie-mysql:3306/hilfie?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=hilfie-elasticsearch:9300
        ports:
            - 8080:8080
    hilfie-mysql:
        extends:
            file: mysql.yml
            service: hilfie-mysql
    hilfie-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: hilfie-elasticsearch
